### ISSUE TITLE
Enabling Universal fluid bucket during PRE-INIT phase causes a crash.

### ISSUE THREAD

**Issue by sp-guip** [faceofcat/Mekfarm#18]
Forge does not like it when you enable universal buckets in a non static way...
[Client thread/ERROR] [FML/mekfarm]: Trying to activate the universal filled bucket too late. Call it statically in your Mods class. Mod: MekFarm.
...

Mod version:0.62+(problem with dung blocks):
Lib version: 0.7
crash report:
Caused by: java.lang.IllegalArgumentException: Empty string not allowed
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:22)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:134)
	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:108)
	at net.minecraftforge.fluids.UniversalBucket.getFilledBucket(UniversalBucket.java:265)
	at mekfarm.blocks.DungBlock.register(DungBlock.java:44)
	at mekfarm.common.BlocksRegistry.createBlocks(BlocksRegistry.java:87)
	at mekfarm.common.CommonProxy.preInit(CommonProxy.java:18)
	at mekfarm.client.ClientProxy.preInit(ClientProxy.java:20)
	at mekfarm.MekfarmMod.preInit(MekfarmMod.java:80)

**Comment by SonOfDiablo** [comment]
I have to same issue when I added Mekfarm to my instance.
TESLA: 1.3.0.51
Tesla Core Lib: 0.7.0
Mekfarm: 0.7.3

Crash Report:
`	Caught exception from MekFarm (mekfarm)
java.lang.IllegalArgumentException: Empty string not allowed
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:22)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:134)
	at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:108)
	at net.minecraftforge.fluids.UniversalBucket.getFilledBucket(UniversalBucket.java:265)
	at mekfarm.blocks.DungBlock.register(DungBlock.java:41)
	at mekfarm.common.BlocksRegistry.createBlocks(BlocksRegistry.java:86)
	at mekfarm.common.CommonProxy.preInit(CommonProxy.java:18)
	at mekfarm.client.ClientProxy.preInit(ClientProxy.java:20)
	at mekfarm.MekfarmMod.preInit(MekfarmMod.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:276)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`
